#!/bin/sh
# Code generated by AI (Claude Opus 5)

set -eu

dir="$(realpath "$(dirname "$0")")"
root="$dir/../.."

bump_minor() {
  echo "$1" | awk -F. '{ print $1 "." $2 + 1 ".0" }'
}

bump_plugin() {
  plugin_dir="$root/plugins/$1"
  old="$(sed -n 's/^version: //p' "$plugin_dir/apm.yml")"
  new="$(bump_minor "$old")"
  sed -i "s/^version: $old$/version: $new/" "$plugin_dir/apm.yml"
  find "$plugin_dir" -maxdepth 2 -name plugin.json -exec sed -i "s/\"$old\"/\"$new\"/" {} +
}

"$dir/updater.sh"

touched_plugins="$(git -C "$root" status --porcelain -- plugins | cut -c4- | cut -d/ -f2 | sort -u)"
for plugin in $touched_plugins; do
  bump_plugin "$plugin"
done

if ! command -v apm >/dev/null 2>&1; then
  curl -fSL https://aka.ms/apm-unix | sh
fi
(cd "$root" && apm pack)
