// Code generated by AI (claude-sonnet-5)

'use strict'

const assert = require('node:assert/strict')
const { spawnSync } = require('node:child_process')
const fs = require('node:fs')
const path = require('node:path')
const { test } = require('node:test')

const PLUGIN_ROOT = path.join(__dirname, '..')
const HOOK = path.join(PLUGIN_ROOT, 'scripts', 'caveman-autostart.js')
const RULES = fs.readFileSync(path.join(PLUGIN_ROOT, 'rules', 'caveman-activate.md'), 'utf8').trim()

const runHook = (env) => spawnSync(process.execPath, [HOOK], {
    env: { ...process.env, PLUGIN_ROOT, CLAUDE_PLUGIN_ROOT: '', CAVEMAN_LEVEL: '', ...env },
    encoding: 'utf8',
})

// --- every SessionStart invocation injects the rules file verbatim, matching upstream's own
// caveman-activate.js hook, which fires unconditionally regardless of the 'source' payload field ---

test('injects the rules file verbatim', () => {
    const { status, stdout } = runHook()
    assert.equal(status, 0)
    const body = JSON.parse(stdout)
    assert.equal(body.additionalContext, RULES)
    assert.equal(body.hookSpecificOutput.hookEventName, 'SessionStart')
})

test('output merges the hookSpecificOutput wrapper with a flat additionalContext field', () => {
    const { stdout } = runHook()
    const body = JSON.parse(stdout)
    assert.equal(body.hookSpecificOutput.additionalContext, body.additionalContext)
})

test('CLAUDE_PLUGIN_ROOT is used when PLUGIN_ROOT is unset', () => {
    const { status, stdout } = runHook({ PLUGIN_ROOT: '', CLAUDE_PLUGIN_ROOT: PLUGIN_ROOT })
    assert.equal(status, 0)
    const body = JSON.parse(stdout)
    assert.equal(body.additionalContext, RULES)
})

test('PLUGIN_ROOT takes precedence over CLAUDE_PLUGIN_ROOT', () => {
    const { status, stdout } = runHook({ CLAUDE_PLUGIN_ROOT: '/nonexistent' })
    assert.equal(status, 0)
    const body = JSON.parse(stdout)
    assert.equal(body.additionalContext, RULES)
})

// --- CAVEMAN_LEVEL environment variable, when set, is appended after the pure rules content ---

test('unset CAVEMAN_LEVEL appends nothing after the rules content', () => {
    const { stdout } = runHook()
    const body = JSON.parse(stdout)
    assert.equal(body.additionalContext, RULES)
})

test('CAVEMAN_LEVEL is appended verbatim after the pure rules content', () => {
    const { stdout } = runHook({ CAVEMAN_LEVEL: 'ultra' })
    const body = JSON.parse(stdout)
    assert.equal(body.additionalContext, `${RULES}\n\nActive level: ultra`)
})
