# Code generated by kickr; DO NOT EDIT.

import "scripts/just/clean.just"
import? "scripts/just/custom.just"

# docs module commands.
mod docs "docs/Justfile"

# list available recipes.
default:
    @just --list
