# Code generated by AI (claude-sonnet-5)

import json
import os
import subprocess

from pathlib import Path
from typing import Any

_SCRIPT = Path(__file__).parent / "scripts" / "codegraph-hook"

def _run(event: str, tool_input: dict[str, Any]) -> dict[str, str] | None:
    payload = json.dumps({"tool_input": tool_input, "cwd": os.getcwd()})
    result = subprocess.run(
        ["node", str(_SCRIPT), event],
        input=payload,
        capture_output=True,
        text=True,
        check=False,
    )
    if not result.stdout:
        return None

    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError:
        return None

def _pre_llm_call(ctx: Any, **kwargs: Any) -> dict[str, str] | None:
    # pre_llm_call is the only Hermes hook that injects context
    result = _run("SessionStart", {})
    context = result.get("context") if result else None
    return {"context": context} if context else None

def register(ctx: Any) -> None:
    ctx.register_hook("pre_llm_call", _pre_llm_call)

    skills_dir = Path(__file__).parent / "skills"
    for child in sorted(skills_dir.iterdir()):
        skill_md = child / "SKILL.md"
        if child.is_dir() and skill_md.exists():
            ctx.register_skill(child.name, skill_md)
