#!/usr/bin/env node
// Code generated by AI (Claude Opus 5)

// UserPromptSubmit hook: parses a mode change out of the prompt and saves it.
// Writes nothing to stdout.

'use strict'

const fs = require('node:fs')
const os = require('node:os')

const { getDefaultMode, readSessionModeRaw, writeSessionMode } = require('./vendor/caveman-config')
const { parseModeChange } = require('./vendor/caveman-parse')

// stateDir is flexible to support multiple runtimes installation mode.
const stateDir = () => process.env.PLUGIN_DATA
    || process.env.CLAUDE_PLUGIN_DATA
    || process.env.COPILOT_PLUGIN_DATA
    || path.join(os.homedir(), '.agents')

const sessionMode = (sessionId, cwd) => {
    const mode = readSessionModeRaw(stateDir(), sessionId) || getDefaultMode(cwd)
    return mode === 'off' ? null : mode
}

// Runtime formats:
//  - most runtimes: session_id
//  - Cursor: conversation_id
const sessionOf = (data) => data.session_id || data.conversation_id

// Runtime formats:
//  - most runtimes: cwd
//  - Cursor: workspace_roots[0] (when cwd is absent)
const cwdOf = (data) => data.cwd || (data.workspace_roots || [])[0]

const main = (data) => {
    const change = parseModeChange(data.prompt, { getDefaultMode: () => getDefaultMode(cwdOf(data)) })
    if (!change) {
        return
    }
    if (change.action === 'clear') {
        writeSessionMode(stateDir(), sessionOf(data), null)
    }
    if (change.action === 'set') {
        writeSessionMode(stateDir(), sessionOf(data), change.mode)
    }
}

if (require.main === module) {
    let payload = {}
    try {
        payload = JSON.parse(fs.readFileSync(0, 'utf8'))
    } catch {
        return
    }

    main(payload)
} else {
    module.exports = { sessionMode } // export for caveman-activate.js
}
