# Code generated by AI (claude-sonnet-5)

import json
import os
import subprocess

from pathlib import Path
from typing import Any, Optional

_SCRIPT = Path(__file__).parent / "scripts" / "protected-paths"

def _pre_tool_call(tool_name: str, args: dict[str, Any], task_id: str = "", **kwargs: Any) -> Optional[dict[str, Any]]:
    payload = json.dumps({"tool_input": args, "cwd": os.getcwd()})
    result = subprocess.run(
        ["node", str(_SCRIPT)],
        input=payload,
        capture_output=True,
        text=True,
        check=False,
    )
    if not result.stdout:
        return None

    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError:
        return None

def register(ctx: Any) -> None:
    ctx.register_hook("pre_tool_call", _pre_tool_call)
