#!/bin/bash
# Code generated by AI (claude-sonnet-5).

set -uo pipefail

script_dir="$(dirname "$(realpath "$0")")"
hook="$script_dir/../scripts/protected-paths.sh"
test_home="/home/tester"

pass=0
fail=0

# assert_allow runs the hook with $1 as stdin and expects a silent, zero-exit allow.
assert_allow() {
  local name="$1" input="$2" output status
  output=$(HOME="$test_home" bash "$hook" <<<"$input" 2>/dev/null)
  status=$?

  if [ "$status" -eq 0 ] && [ -z "$output" ]; then
    echo "PASS: $name"
    pass=$((pass + 1))
  else
    echo "FAIL: $name (expected silent allow, got exit=$status output='$output')"
    fail=$((fail + 1))
  fi
}

# assert_deny runs the hook with $2 as stdin and expects a deny JSON body referencing $3.
assert_deny() {
  local name="$1" input="$2" pattern="$3" output status
  output=$(HOME="$test_home" bash "$hook" <<<"$input" 2>/dev/null)
  status=$?

  if [ "$status" -eq 0 ] &&
    grep -q '"permissionDecision": *"deny"' <<<"$output" &&
    grep -q "$pattern" <<<"$output"; then
    echo "PASS: $name"
    pass=$((pass + 1))
  else
    echo "FAIL: $name (expected deny matching '$pattern', got exit=$status output='$output')"
    fail=$((fail + 1))
  fi
}

# --- normal calls: nothing protected is referenced ---

assert_allow "normal command" \
  '{"tool_input":{"command":"echo hello-world"}}'

assert_allow "claude transcript_path is bookkeeping, not a tool argument" \
  '{"transcript_path":"~/.claude/projects/foo/session.jsonl","tool_input":{"command":"echo hi"}}'

# --- allow-listed subpaths stay usable despite their parent dir being denied ---

assert_allow "claude CLAUDE.md is allow-listed" \
  '{"tool_input":{"command":"cat ~/.claude/CLAUDE.md"}}'

assert_allow "claude rules dir is allow-listed" \
  '{"tool_input":{"command":"cat ~/.claude/rules/shell.md"}}'

assert_allow "codex skills dir is allow-listed" \
  '{"tool_input":{"command":"ls ~/.codex/skills"}}'

assert_allow "apm apm_modules is allow-listed" \
  '{"tool_input":{"command":"ls ~/.apm/apm_modules"}}'

assert_allow "copilot personal instructions file is allow-listed" \
  '{"tool_input":{"command":"cat ~/.copilot/copilot-instructions.md"}}'

assert_allow "copilot instructions dir is allow-listed" \
  '{"tool_input":{"command":"ls ~/.copilot/instructions"}}'

# shellcheck disable=SC2016
assert_allow "literal \$HOME text is normalized before allow-listing" \
  '{"tool_input":{"command":"cat $HOME/.claude/CLAUDE.md"}}'

# --- protected directories are denied outside of their allow-listed subpaths ---

assert_deny "claude settings.json is denied" \
  '{"tool_input":{"command":"cat ~/.claude/settings.json"}}' \
  '.claude'

assert_deny "copilot mcp config is denied" \
  '{"tool_input":{"command":"cat ~/.copilot/mcp-config.json"}}' \
  '.copilot'

assert_deny "codex auth.json is denied" \
  '{"tool_input":{"command":"cat ~/.codex/auth.json"}}' \
  '.codex'

assert_deny "apm config outside the allow-list is denied" \
  '{"tool_input":{"command":"cat ~/.apm/credentials.json"}}' \
  '.apm'

assert_deny "ssh key is denied" \
  '{"tool_input":{"command":"cat ~/.ssh/id_rsa"}}' \
  '.ssh'

assert_deny "aws credentials are denied" \
  '{"tool_input":{"command":"cat ~/.aws/credentials"}}' \
  '.aws'

# --- the hook scans the raw payload, so it works across each agent's own field names ---
# Codex PreToolUse payload shape: https://developers.openai.com/codex/hooks
# Copilot preToolUse payload shape: https://docs.github.com/en/copilot/reference/hooks-reference

assert_deny "codex's native payload shape (tool_name/tool_input, snake_case) is still scanned" \
  '{"session_id":"s1","turn_id":"t1","tool_name":"Bash","tool_use_id":"u1","tool_input":{"command":"cat ~/.ssh/id_rsa"},"cwd":"/repo","hook_event_name":"PreToolUse","model":"gpt","permission_mode":"default"}' \
  '.ssh'

assert_allow "codex's native payload shape allow-lists AGENTS.md the same way" \
  '{"session_id":"s1","turn_id":"t1","tool_name":"Bash","tool_use_id":"u1","tool_input":{"command":"cat ~/.codex/AGENTS.md"},"cwd":"/repo","hook_event_name":"PreToolUse","model":"gpt","permission_mode":"default"}'

assert_deny "copilot's native payload shape (toolName/toolArgs, camelCase) is still scanned" \
  '{"sessionId":"s1","timestamp":1704614400000,"cwd":"/repo","toolName":"bash","toolArgs":{"command":"cat ~/.copilot/mcp-config.json"}}' \
  '.copilot'

assert_deny "copilot's toolArgs, when double-encoded as an escaped JSON string, is still scanned" \
  '{"sessionId":"s1","timestamp":1704614400000,"cwd":"/repo","toolName":"bash","toolArgs":"{\"command\":\"cat ~/.ssh/id_rsa\"}"}' \
  '.ssh'

assert_allow "copilot's native payload shape allow-lists its instructions file the same way" \
  '{"sessionId":"s1","timestamp":1704614400000,"cwd":"/repo","toolName":"bash","toolArgs":{"command":"cat ~/.copilot/copilot-instructions.md"}}'

# --- compound and adversarial calls ---

assert_deny "an allowed path chained with a denied one still denies" \
  '{"tool_input":{"command":"cat ~/.claude/CLAUDE.md; cat ~/.ssh/id_rsa"}}' \
  '.ssh'

assert_deny "a '..' traversal segment disables the allow-list entirely" \
  '{"tool_input":{"command":"cat ~/.claude/CLAUDE.md/../../.ssh/id_rsa"}}' \
  '.claude'

echo
echo "$pass passed, $fail failed"
[ "$fail" -eq 0 ]
