// Code generated by AI (claude-sonnet-5)

'use strict';

const assert = require('node:assert/strict');
const { spawnSync } = require('node:child_process');
const path = require('node:path');
const { test } = require('node:test');

const HOOK = path.join(__dirname, '..', 'scripts', 'protected-paths.js');
const TEST_HOME = '/home/tester';

const runHook = (input) => spawnSync(process.execPath, [HOOK], {
  input,
  env: { ...process.env, HOME: TEST_HOME },
  encoding: 'utf8',
});

// --- normal calls: nothing protected is referenced ---

test('normal command', () => {
  const { status, stdout } = runHook('{"tool_input":{"command":"echo hello-world"}}');
  assert.equal(status, 0);
  assert.equal(stdout, '');
});

test('claude transcript_path is bookkeeping, not a tool argument', () => {
  const { status, stdout } = runHook('{"transcript_path":"~/.claude/projects/foo/session.jsonl","tool_input":{"command":"echo hi"}}');
  assert.equal(status, 0);
  assert.equal(stdout, '');
});

// --- allow-listed subpaths stay usable despite their parent dir being denied ---

test('claude CLAUDE.md is allow-listed', () => {
  const { status, stdout } = runHook('{"tool_input":{"command":"cat ~/.claude/CLAUDE.md"}}');
  assert.equal(status, 0);
  assert.equal(stdout, '');
});

test('claude rules dir is allow-listed', () => {
  const { status, stdout } = runHook('{"tool_input":{"command":"cat ~/.claude/rules/shell.md"}}');
  assert.equal(status, 0);
  assert.equal(stdout, '');
});

test('codex skills dir is allow-listed', () => {
  const { status, stdout } = runHook('{"tool_input":{"command":"ls ~/.codex/skills"}}');
  assert.equal(status, 0);
  assert.equal(stdout, '');
});

test('apm apm_modules is allow-listed', () => {
  const { status, stdout } = runHook('{"tool_input":{"command":"ls ~/.apm/apm_modules"}}');
  assert.equal(status, 0);
  assert.equal(stdout, '');
});

test('copilot personal instructions file is allow-listed', () => {
  const { status, stdout } = runHook('{"tool_input":{"command":"cat ~/.copilot/copilot-instructions.md"}}');
  assert.equal(status, 0);
  assert.equal(stdout, '');
});

test('copilot instructions dir is allow-listed', () => {
  const { status, stdout } = runHook('{"tool_input":{"command":"ls ~/.copilot/instructions"}}');
  assert.equal(status, 0);
  assert.equal(stdout, '');
});

test('literal $HOME text is normalized before allow-listing', () => {
  const { status, stdout } = runHook('{"tool_input":{"command":"cat $HOME/.claude/CLAUDE.md"}}');
  assert.equal(status, 0);
  assert.equal(stdout, '');
});

// --- protected directories are denied outside of their allow-listed subpaths ---

test('claude settings.json is denied', () => {
  const { status, stdout } = runHook('{"tool_input":{"command":"cat ~/.claude/settings.json"}}');
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('.claude'), "expected deny output to include '.claude'");
});

test('copilot mcp config is denied', () => {
  const { status, stdout } = runHook('{"tool_input":{"command":"cat ~/.copilot/mcp-config.json"}}');
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('.copilot'), "expected deny output to include '.copilot'");
});

test('codex auth.json is denied', () => {
  const { status, stdout } = runHook('{"tool_input":{"command":"cat ~/.codex/auth.json"}}');
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('.codex'), "expected deny output to include '.codex'");
});

test('apm config outside the allow-list is denied', () => {
  const { status, stdout } = runHook('{"tool_input":{"command":"cat ~/.apm/credentials.json"}}');
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('.apm'), "expected deny output to include '.apm'");
});

test('ssh key is denied', () => {
  const { status, stdout } = runHook('{"tool_input":{"command":"cat ~/.ssh/id_rsa"}}');
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('.ssh'), "expected deny output to include '.ssh'");
});

test('aws credentials are denied', () => {
  const { status, stdout } = runHook('{"tool_input":{"command":"cat ~/.aws/credentials"}}');
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('.aws'), "expected deny output to include '.aws'");
});

// --- the hook scans the raw payload, so it works across each agent's own field names ---
// Codex PreToolUse payload shape: https://developers.openai.com/codex/hooks
// Copilot preToolUse payload shape: https://docs.github.com/en/copilot/reference/hooks-reference

test("codex's native payload shape (tool_name/tool_input, snake_case) is still scanned", () => {
  const { status, stdout } = runHook(
    '{"session_id":"s1","turn_id":"t1","tool_name":"Bash","tool_use_id":"u1","tool_input":{"command":"cat ~/.ssh/id_rsa"},"cwd":"/repo","hook_event_name":"PreToolUse","model":"gpt","permission_mode":"default"}',
  );
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('.ssh'), "expected deny output to include '.ssh'");
});

test("codex's native payload shape allow-lists AGENTS.md the same way", () => {
  const { status, stdout } = runHook(
    '{"session_id":"s1","turn_id":"t1","tool_name":"Bash","tool_use_id":"u1","tool_input":{"command":"cat ~/.codex/AGENTS.md"},"cwd":"/repo","hook_event_name":"PreToolUse","model":"gpt","permission_mode":"default"}',
  );
  assert.equal(status, 0);
  assert.equal(stdout, '');
});

test("copilot's native payload shape (toolName/toolArgs, camelCase) is still scanned", () => {
  const { status, stdout } = runHook(
    '{"sessionId":"s1","timestamp":1704614400000,"cwd":"/repo","toolName":"bash","toolArgs":{"command":"cat ~/.copilot/mcp-config.json"}}',
  );
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('.copilot'), "expected deny output to include '.copilot'");
});

test("copilot's toolArgs, when double-encoded as an escaped JSON string, is still scanned", () => {
  const { status, stdout } = runHook(
    '{"sessionId":"s1","timestamp":1704614400000,"cwd":"/repo","toolName":"bash","toolArgs":"{\\"command\\":\\"cat ~/.ssh/id_rsa\\"}"}',
  );
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('.ssh'), "expected deny output to include '.ssh'");
});

test("copilot's native payload shape allow-lists its instructions file the same way", () => {
  const { status, stdout } = runHook(
    '{"sessionId":"s1","timestamp":1704614400000,"cwd":"/repo","toolName":"bash","toolArgs":{"command":"cat ~/.copilot/copilot-instructions.md"}}',
  );
  assert.equal(status, 0);
  assert.equal(stdout, '');
});

// --- compound and adversarial calls ---

test('an allowed path chained with a denied one still denies', () => {
  const { status, stdout } = runHook('{"tool_input":{"command":"cat ~/.claude/CLAUDE.md; cat ~/.ssh/id_rsa"}}');
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('.ssh'), "expected deny output to include '.ssh'");
});

test("a '..' traversal segment resolves to its real, denied destination", () => {
  const { status, stdout } = runHook('{"tool_input":{"command":"cat ~/.claude/CLAUDE.md/../../.ssh/id_rsa"}}');
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('.ssh'), "expected deny output to include '.ssh'");
});

// --- recursive tools scanning an ancestor of a protected dir must be denied too, without ---
// --- needing to recognize the specific recursive flag/command being used ---

test('grep -r over the whole home dir reaches every protected dir', () => {
  const { status, stdout } = runHook('{"tool_input":{"command":"grep -r password ~"}}');
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('ancestor of protected path'), "expected deny output to include 'ancestor of protected path'");
});

test('find over $HOME reaches every protected dir', () => {
  const { status, stdout } = runHook('{"tool_input":{"command":"find $HOME -name id_rsa"}}');
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('ancestor of protected path'), "expected deny output to include 'ancestor of protected path'");
});

test('a bare cd into the home dir is an ancestor of every protected dir', () => {
  const { status, stdout } = runHook('{"tool_input":{"command":"cd ~"}}');
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('ancestor of protected path'), "expected deny output to include 'ancestor of protected path'");
});

// --- known-fields JSON parsing: non-command fields are scanned too, malformed input fails closed ---

test('a Read-style file_path field is scanned the same way as command', () => {
  const { status, stdout } = runHook('{"tool_input":{"file_path":"~/.ssh/id_rsa"}}');
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('.ssh'), "expected deny output to include '.ssh'");
});

test("a Grep-style glob field is scanned separately from pattern", () => {
  const { status, stdout } = runHook('{"tool_input":{"pattern":"password","path":".","glob":"~/.ssh/*"}}');
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('.ssh'), "expected deny output to include '.ssh'");
});

test('malformed JSON payload is denied rather than silently allowed', () => {
  const { status, stdout } = runHook('not json');
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('not valid JSON'), "expected deny output to include 'not valid JSON'");
});
