// Code generated by AI (Claude Sonnet 5)

'use strict';

const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const assert = require('node:assert/strict');
const { spawnSync } = require('node:child_process');
const { test } = require('node:test');

const HOOK = path.join(__dirname, '..', 'scripts', 'protected-paths.js');

// FIXTURE_CONFIG covers the paths the tests below reference.
const FIXTURE_CONFIG = {
  denylist: ['~/.agents', '~/.apm', '~/.aws', '~/.claude', '~/.codex', '~/.config', '~/.copilot', '~/.ssh'],
  allowlist: ['~/.claude/CLAUDE.md'],
};

// makeHome creates a throwaway HOME directory, optionally seeded with a config.json body
// (an object is serialized, a string is written verbatim to test malformed JSON).
const makeHome = (configBody) => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'protected-paths-'));
  if (configBody === null) return dir;

  const configPath = path.join(dir, '.config', 'protected-paths', 'config.json');
  fs.mkdirSync(path.dirname(configPath), { recursive: true });
  fs.writeFileSync(configPath, typeof configBody === 'string' ? configBody : JSON.stringify(configBody));
  return dir;
};

const TEST_HOME = makeHome(FIXTURE_CONFIG);
const NO_CONFIG_HOME = makeHome(null);
const MALFORMED_CONFIG_HOME = makeHome('not json');

const runHook = (input, home = TEST_HOME) => spawnSync(process.execPath, [HOOK], {
  input,
  env: { ...process.env, HOME: home },
  encoding: 'utf8',
});

// --- config loading: no config file, or a malformed one, means every call is allowed ---

test('no config file present allows every call', () => {
  const { status, stdout } = runHook('{"tool_input":{"command":"cat ~/.ssh/id_rsa"}}', NO_CONFIG_HOME);
  assert.equal(status, 0);
  assert.equal(stdout, '');
});

test('a malformed config.json is treated as absent, allowing every call', () => {
  const { status, stdout } = runHook('{"tool_input":{"command":"cat ~/.ssh/id_rsa"}}', MALFORMED_CONFIG_HOME);
  assert.equal(status, 0);
  assert.equal(stdout, '');
});

// --- normal calls: nothing protected is referenced ---

test('normal command', () => {
  const { status, stdout } = runHook('{"tool_input":{"command":"echo hello-world"}}');
  assert.equal(status, 0);
  assert.equal(stdout, '');
});

test('claude transcript_path is bookkeeping, not a tool argument', () => {
  const { status, stdout } = runHook('{"transcript_path":"~/.claude/projects/foo/session.jsonl","tool_input":{"command":"echo hi"}}');
  assert.equal(status, 0);
  assert.equal(stdout, '');
});

// --- protected directories are denied outside of their allow-listed subpaths ---

test('claude config.json is denied', () => {
  const { status, stdout } = runHook('{"tool_input":{"command":"cat ~/.claude/config.json"}}');
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('.claude'), "expected deny output to include '.claude'");
});

test('copilot config.json is denied', () => {
  const { status, stdout } = runHook('{"tool_input":{"command":"cat ~/.copilot/config.json"}}');
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('.copilot'), "expected deny output to include '.copilot'");
});

test('agents dir outside its skills allow-list is denied', () => {
  const { status, stdout } = runHook('{"tool_input":{"command":"cat ~/.agents/state.json"}}');
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('.agents'), "expected deny output to include '.agents'");
});

test('config dir outside devin allow-list is denied', () => {
  const { status, stdout } = runHook('{"tool_input":{"command":"cat ~/.config/some-other-app/secrets.json"}}');
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('.config'), "expected deny output to include '.config'");
});

test('codex auth.json is denied', () => {
  const { status, stdout } = runHook('{"tool_input":{"command":"cat ~/.codex/auth.json"}}');
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('.codex'), "expected deny output to include '.codex'");
});

test('apm config outside the allow-list is denied', () => {
  const { status, stdout } = runHook('{"tool_input":{"command":"cat ~/.apm/credentials.json"}}');
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('.apm'), "expected deny output to include '.apm'");
});

test('ssh key is denied', () => {
  const { status, stdout } = runHook('{"tool_input":{"command":"cat ~/.ssh/id_rsa"}}');
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('.ssh'), "expected deny output to include '.ssh'");
});

test('aws credentials are denied', () => {
  const { status, stdout } = runHook('{"tool_input":{"command":"cat ~/.aws/credentials"}}');
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('.aws'), "expected deny output to include '.aws'");
});

// --- the hook scans the raw payload, so it works across each agent's own field names ---
// Codex PreToolUse payload shape: https://developers.openai.com/codex/hooks
// Copilot preToolUse payload shape: https://docs.github.com/en/copilot/reference/hooks-reference

test("codex's native payload shape (tool_name/tool_input, snake_case) is still scanned", () => {
  const { status, stdout } = runHook(
    '{"session_id":"s1","turn_id":"t1","tool_name":"Bash","tool_use_id":"u1","tool_input":{"command":"cat ~/.ssh/id_rsa"},"cwd":"/repo","hook_event_name":"PreToolUse","model":"gpt","permission_mode":"default"}',
  );
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('.ssh'), "expected deny output to include '.ssh'");
});

test("copilot's native payload shape (toolName/toolArgs, camelCase) is still scanned", () => {
  const { status, stdout } = runHook(
    '{"sessionId":"s1","timestamp":1704614400000,"cwd":"/repo","toolName":"bash","toolArgs":{"command":"cat ~/.copilot/config.json"}}',
  );
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('.copilot'), "expected deny output to include '.copilot'");
});

test("copilot's toolArgs, when double-encoded as an escaped JSON string, is still scanned", () => {
  const { status, stdout } = runHook(
    '{"sessionId":"s1","timestamp":1704614400000,"cwd":"/repo","toolName":"bash","toolArgs":"{\\"command\\":\\"cat ~/.ssh/id_rsa\\"}"}',
  );
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('.ssh'), "expected deny output to include '.ssh'");
});

test("cursor's native payload shape is scanned and denied with cursor's own decision field", () => {
  const { status, stdout } = runHook(
    '{"tool_name":"Shell","tool_input":{"command":"cat ~/.ssh/id_rsa","working_directory":"/repo"},"tool_use_id":"u1","cwd":"/repo"}',
  );
  assert.equal(status, 0);
  assert.match(stdout, /"permission":\s*"deny"/);
  assert.ok(stdout.includes('.ssh'), "expected deny output to include '.ssh'");
});

test('an absolute_path argument is scanned the same way as file_path', () => {
  const { status, stdout } = runHook(`{"tool_name":"read_file","tool_input":{"absolute_path":"${TEST_HOME}/.ssh/id_rsa"}}`);
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('.ssh'), "expected deny output to include '.ssh'");
});

// --- compound and adversarial calls ---

test('an allowed path chained with a denied one still denies', () => {
  const { status, stdout } = runHook('{"tool_input":{"command":"cat ~/.claude/CLAUDE.md; cat ~/.ssh/id_rsa"}}');
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('.ssh'), "expected deny output to include '.ssh'");
});

test("a '..' traversal segment resolves to its real, denied destination", () => {
  const { status, stdout } = runHook('{"tool_input":{"command":"cat ~/.claude/CLAUDE.md/../../.ssh/id_rsa"}}');
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('.ssh'), "expected deny output to include '.ssh'");
});

// --- recursive tools scanning an ancestor of a protected dir must be denied too, without ---
// --- needing to recognize the specific recursive flag/command being used ---

test('grep -r over the whole home dir reaches every protected dir', () => {
  const { status, stdout } = runHook('{"tool_input":{"command":"grep -r password ~"}}');
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('ancestor of protected path'), "expected deny output to include 'ancestor of protected path'");
});

test('find over $HOME reaches every protected dir', () => {
  const { status, stdout } = runHook('{"tool_input":{"command":"find $HOME -name id_rsa"}}');
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('ancestor of protected path'), "expected deny output to include 'ancestor of protected path'");
});

test('a bare cd into the home dir is an ancestor of every protected dir', () => {
  const { status, stdout } = runHook('{"tool_input":{"command":"cd ~"}}');
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('ancestor of protected path'), "expected deny output to include 'ancestor of protected path'");
});

// --- known-fields JSON parsing: non-command fields are scanned too, malformed input fails closed ---

test('a Read-style file_path field is scanned the same way as command', () => {
  const { status, stdout } = runHook('{"tool_input":{"file_path":"~/.ssh/id_rsa"}}');
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('.ssh'), "expected deny output to include '.ssh'");
});

test("a Grep-style glob field is scanned separately from pattern", () => {
  const { status, stdout } = runHook('{"tool_input":{"pattern":"password","path":".","glob":"~/.ssh/*"}}');
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('.ssh'), "expected deny output to include '.ssh'");
});

// --- relative references are resolved against the tool call's own cwd, not the hook's ---

test('a relative command reference resolved against cwd is denied', () => {
  const { status, stdout } = runHook(`{"cwd":"${TEST_HOME}/project","tool_input":{"command":"cat ../.ssh/id_rsa"}}`);
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('.ssh'), "expected deny output to include '.ssh'");
});

test('a relative file_path resolved against cwd is denied', () => {
  const { status, stdout } = runHook(`{"cwd":"${TEST_HOME}/project","tool_input":{"file_path":"../.ssh/id_rsa"}}`);
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('.ssh'), "expected deny output to include '.ssh'");
});

test('a relative reference outside any protected dir is allowed', () => {
  const { status, stdout } = runHook(`{"cwd":"${TEST_HOME}/project","tool_input":{"command":"cat ../notes.txt"}}`);
  assert.equal(status, 0);
  assert.equal(stdout, '');
});

test('malformed JSON payload is denied rather than silently allowed', () => {
  const { status, stdout } = runHook('not json');
  assert.equal(status, 0);
  assert.match(stdout, /"permissionDecision":\s*"deny"/);
  assert.ok(stdout.includes('not valid JSON'), "expected deny output to include 'not valid JSON'");
});
