#!/usr/bin/env node
// Code generated by AI (claude-sonnet-5)

'use strict'

const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')

const HOME = os.homedir()

const ALLOW_LIST = [
    // apm
    `${HOME}/.apm/apm.yml`,
    `${HOME}/.apm/apm_modules`,
    `${HOME}/.apm/cache`,
    `${HOME}/.apm/config.json`,
    `${HOME}/.apm/marketplaces.json`,
    // claude
    `${HOME}/.claude/CLAUDE.md`,
    `${HOME}/.claude/agent-memory`,
    `${HOME}/.claude/agents`,
    `${HOME}/.claude/commands`,
    `${HOME}/.claude/hooks`,
    `${HOME}/.claude/output-styles`,
    `${HOME}/.claude/plugins`,
    `${HOME}/.claude/rules`,
    `${HOME}/.claude/skills`,
    `${HOME}/.claude/workflows`,
    // codex
    `${HOME}/.codex/AGENTS.md`,
    `${HOME}/.codex/hooks.json`,
    `${HOME}/.codex/plugins`,
    `${HOME}/.codex/skills`,
    // copilot
    `${HOME}/.copilot/agents`,
    `${HOME}/.copilot/copilot-instructions.md`,
    `${HOME}/.copilot/hooks`,
    `${HOME}/.copilot/installed-plugins`,
    `${HOME}/.copilot/instructions`,
    `${HOME}/.copilot/prompts`,
    `${HOME}/.copilot/skills`,
]

const DENY_LIST = [
    `${HOME}/.agents`,
    `${HOME}/.apm`,
    `${HOME}/.aws`,
    `${HOME}/.azure`,
    `${HOME}/.claude`,
    `${HOME}/.codex`,
    `${HOME}/.config`,
    `${HOME}/.copilot`,
    `${HOME}/.docker`,
    `${HOME}/.git-credentials`,
    `${HOME}/.gnupg`,
    `${HOME}/.kube`,
    `${HOME}/.netrc`,
    `${HOME}/.npmrc`,
    `${HOME}/.pypirc`,
    `${HOME}/.ssh`,
]

// every absolute-path-looking token in a scanned field stops at whitespace/quotes/shell metacharacters
const TOKEN_PATTERN = /\/[^\]\s"\\;|&()<>,}]*/g

// tool-argument fields, across Claude/Codex/Copilot's built-in tools, that can carry a filesystem
// path. A field or tool not listed here (eg. a custom MCP tool's own argument shape) is not scanned -
// the accepted tradeoff for parsing known JSON fields instead of scanning the raw payload text.
const KNOWN_FIELDS = ['command', 'file_path', 'path', 'notebook_path', 'pattern', 'glob', 'directory']

// toolInputOf returns the tool-call argument object of a hook payload, regardless of which agent
// sent it: Claude/Codex use tool_input, Copilot uses toolArgs - sometimes as a plain object,
// sometimes double-encoded as an escaped JSON string.
const toolInputOf = (payload) => {
    let toolInput = payload.tool_input ?? payload.toolArgs ?? {}
    if (typeof toolInput === 'string') {
        try {
            toolInput = JSON.parse(toolInput)
        } catch {
            toolInput = {}
        }
    }
    return toolInput
}

// isPrefix reports whether prefix is target itself, or an ancestor directory of target.
const isPrefix = (prefix, target) => target === prefix || target.startsWith(`${prefix}/`)

// resolvePath mimics `realpath -m`: it canonicalizes every existing leading segment
// (resolving symlinks) then lexically appends whatever doesn't exist, without requiring
// the full path to exist - so a reference to a not-yet-created file under a protected
// directory is still caught.
const resolvePath = (target) => {
    const segments = path.resolve(target).split(path.sep).filter(Boolean)

    let real = path.sep
    let i = 0
    for (; i < segments.length; i += 1) {
        try {
            real = fs.realpathSync(path.join(real, segments[i]))
        } catch {
            break
        }
    }

    return i === segments.length ? real : path.join(real, ...segments.slice(i))
}

// denyReasonFor returns the deny reason for a resolved path, or null if it's allowed.
const denyReasonFor = (resolved) => {
    for (const pattern of DENY_LIST) {
        if (isPrefix(pattern, resolved)) {
            if (ALLOW_LIST.some((allowed) => isPrefix(allowed, resolved))) {
                return null
            }
            return `tool call references a protected path: '${pattern}'`
        }

        if (isPrefix(resolved, pattern)) {
            return `tool call references an ancestor of protected path: '${pattern}'`
        }
    }
    return null
}

// deny prints an explanatory message on stderr and a deny decision on stdout, then exits 0.
// The JSON body merges Claude/Codex's hookSpecificOutput wrapper with Copilot's flat shape,
// since exiting with an error code alone isn't enough for Copilot to block the tool call.
const deny = (reason) => {
    const body = JSON.stringify({
        permissionDecision: 'deny',
        permissionDecisionReason: reason,
        hookSpecificOutput: {
            hookEventName: 'PreToolUse',
            permissionDecision: 'deny',
            permissionDecisionReason: reason,
        },
    })
    process.stderr.write(`blocked: ${reason}`)
    process.stdout.write(body)
    process.exit(0)
}

const main = () => {
    const input = fs.readFileSync(0, 'utf8')

    let payload
    try {
        payload = JSON.parse(input)
    } catch {
        deny('payload is not valid JSON')
    }

    const toolInput = toolInputOf(payload)
    const values = KNOWN_FIELDS
        .map((field) => toolInput[field])
        .filter((value) => typeof value === 'string')
    if (typeof payload.cwd === 'string') {
        values.push(payload.cwd)
    }

    const tokens = values.flatMap((value) => {
        const normalized = value
            .replaceAll('~', HOME)
            .replaceAll('$HOME', HOME)
            .replaceAll('${HOME}', HOME)
        return normalized.match(TOKEN_PATTERN) ?? []
    })

    for (const token of new Set(tokens)) {
        const reason = denyReasonFor(resolvePath(token))
        if (reason) {
            deny(reason)
        }
    }
}

main()
