#!/usr/bin/env node
// Code generated by AI (Claude Sonnet 5)

'use strict'

const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')

const HOME = os.homedir()
const CONFIG_PATH = path.join(HOME, '.config', 'protected-paths', 'config.json')

// shell-token boundary, used to split path tokens out of compound field values.
const SPLIT_PATTERN = /[\s"'\\;|&()<>,}]+/

// fields whose entire value is a single path.
const SINGLE_PATH_FIELDS = [
    'absolute_path',
    'directory',
    'file_path',
    'notebook_path',
    'path',
    'working_directory',
]

// fields that embed a path inside a larger string (shell command, glob expression).
const COMPOUND_FIELDS = [
    'command',
    'glob',
    'pattern',
]

// toolInputOf extracts the tool-call arguments from a hook payload (tool_input or Copilot's toolArgs, plain or JSON-encoded).
const toolInputOf = (payload) => {
    let toolInput = payload.tool_input ?? payload.toolArgs ?? {}
    if (typeof toolInput === 'string') {
        try {
            toolInput = JSON.parse(toolInput)
        } catch {
            toolInput = {}
        }
    }
    return toolInput
}

const expand = (value) => value
    .replaceAll('~', HOME)
    .replaceAll('$HOME', HOME)
    .replaceAll('${HOME}', HOME)

// loadConfig reads denylist/allowlist from CONFIG_PATH, or null if absent, unreadable, or malformed.
const loadConfig = () => {
    let parsed
    try {
        parsed = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8'))
    } catch {
        return null
    }
    return {
        denylist: (parsed.denylist ?? []).map(expand),
        allowlist: (parsed.allowlist ?? []).map(expand),
    }
}

// isPrefix reports whether target equals prefix or sits under it.
const isPrefix = (prefix, target) => target === prefix || target.startsWith(`${prefix}/`)

// resolvePath resolves target against base (like `realpath -m`), following symlinks on existing segments
// and appending the rest lexically, so a not-yet-created path under a protected dir is still caught.
const resolvePath = (base, target) => {
    const segments = path.resolve(base, target).split(path.sep).filter(Boolean)

    let real = path.sep
    let i = 0
    for (; i < segments.length; i += 1) {
        try {
            real = fs.realpathSync(path.join(real, segments[i]))
        } catch {
            break
        }
    }

    return i === segments.length ? real : path.join(real, ...segments.slice(i))
}

// denyReasonFor returns the deny reason for a resolved path, or null if allowed.
const denyReasonFor = (denylist, allowlist, resolved) => {
    for (const pattern of denylist) {
        if (isPrefix(pattern, resolved)) {
            if (allowlist.some((allowed) => isPrefix(allowed, resolved))) {
                return null
            }
            return `tool call references a protected path: '${pattern}'`
        }

        if (isPrefix(resolved, pattern)) {
            return `tool call references an ancestor of protected path: '${pattern}', target the specific file or subdirectory you need instead of scanning or cd-ing into $HOME`
        }
    }
    return null
}

// deny blocks the tool call with reason, writing every agent's PreToolUse deny format (unknown keys are ignored).
//
// Runtime formats:
//  - Claude Code, Codex: hookSpecificOutput wrapper
//  - Copilot, Codex: flat permissionDecision
//  - Cursor: flat permission
//  - Gemini: flat decision
const deny = (reason) => {
    const body = JSON.stringify({
        action: "block",
        agent_message: reason,
        decision: 'block',
        message: reason,
        permission: 'deny',
        permissionDecision: 'deny',
        permissionDecisionReason: reason,
        reason,
        user_message: reason,
        hookSpecificOutput: {
            hookEventName: 'PreToolUse',
            permissionDecision: 'deny',
            permissionDecisionReason: reason,
        },
    })
    process.stderr.write(`blocked: ${reason}`)
    process.stdout.write(body)
    process.exit(0)
}

const main = (payload) => {
    const config = loadConfig()
    if (!config) {
        return
    }

    const toolInput = toolInputOf(payload)
    const cwd = typeof payload.cwd === 'string' ? payload.cwd : process.cwd()

    const singleValues = SINGLE_PATH_FIELDS
        .map((field) => toolInput[field])
        .filter((value) => typeof value === 'string')
        .map(expand)
    if (typeof payload.cwd === 'string') {
        singleValues.push(cwd)
    }

    const compoundTokens = COMPOUND_FIELDS
        .map((field) => toolInput[field])
        .filter((value) => typeof value === 'string')
        .flatMap((value) => expand(value).split(SPLIT_PATTERN))
        .filter((token) => token.includes('/'))

    const tokens = [...singleValues, ...compoundTokens]
    for (const token of new Set(tokens)) {
        const reason = denyReasonFor(config.denylist, config.allowlist, resolvePath(cwd, token))
        if (reason) {
            deny(reason)
        }
    }
}

try {
    main(JSON.parse(fs.readFileSync(0, 'utf8')))
} catch {
    deny('payload is not valid JSON')
}
