#!/bin/bash
# Code generated by AI (claude-sonnet-5)

set -e

ALLOW_LIST=(
  # apm
  "$HOME/.apm/apm.yml"
  "$HOME/.apm/apm_modules"
  "$HOME/.apm/cache"
  "$HOME/.apm/config.json"
  "$HOME/.apm/marketplaces.json"
  # claude
  "$HOME/.claude/CLAUDE.md"
  "$HOME/.claude/agent-memory"
  "$HOME/.claude/agents"
  "$HOME/.claude/commands"
  "$HOME/.claude/hooks"
  "$HOME/.claude/output-styles"
  "$HOME/.claude/plugins"
  "$HOME/.claude/rules"
  "$HOME/.claude/skills"
  "$HOME/.claude/workflows"
  # codex
  "$HOME/.codex/AGENTS.md"
  "$HOME/.codex/hooks.json"
  "$HOME/.codex/plugins"
  "$HOME/.codex/skills"
  # copilot
  "$HOME/.copilot/agents"
  "$HOME/.copilot/copilot-instructions.md"
  "$HOME/.copilot/hooks"
  "$HOME/.copilot/installed-plugins"
  "$HOME/.copilot/instructions"
  "$HOME/.copilot/prompts"
  "$HOME/.copilot/skills"
)

DENY_LIST=(
  "$HOME/.agents"
  "$HOME/.apm"
  "$HOME/.aws"
  "$HOME/.azure"
  "$HOME/.claude"
  "$HOME/.codex"
  "$HOME/.config"
  "$HOME/.copilot"
  "$HOME/.docker"
  "$HOME/.git-credentials"
  "$HOME/.gnupg"
  "$HOME/.kube"
  "$HOME/.netrc"
  "$HOME/.npmrc"
  "$HOME/.pypirc"
  "$HOME/.ssh"
)

deny() {
  local reason="$1"
  echo "blocked: $reason" >&2
  # copilot needs a whole JSON response, exiting with an error isn't enough
  # merging all valid agents outputs into one to allow each one to get its expected output values
  cat <<EOF
{
  "permissionDecision": "deny",
  "permissionDecisionReason": "$reason",
  "hookSpecificOutput": {
    "hookEventName": "PreToolUse",
    "permissionDecision": "deny",
    "permissionDecisionReason": "$reason"
  }
}
EOF
  exit 0
}

# is_prefix reports whether $1 is $2 itself, or an ancestor directory of $2.
is_prefix() {
  local prefix="$1" path="$2"
  [[ "$path" == "$prefix" || "$path" == "$prefix"/* ]]
}

INPUT=$(cat)
# transcript_path is agent bookkeeping metadata (always under ~/.claude/projects), not a tool
# argument; scanning it would block every single tool call once ~/.claude is denied.
stripped=$(echo "$INPUT" | sed -E 's/"transcript_path"[[:space:]]*:[[:space:]]*"[^"]*"/"transcript_path":""/')
normalized=$(echo "$stripped" | sed "s|~|$HOME|g; s|\$HOME|$HOME|g")

# extract every absolute-path-looking token from the payload and resolve it with realpath
# '..' segments, symlinks, and bare references to an ancestor of a protected dir
# (which recursive tools like grep -r/find/tar could use to reach it without ever naming it) are all caught the same way
# instead of as separate substring patterns.
while IFS= read -r token; do
  [ -z "$token" ] && continue
  resolved=$(realpath -m -- "$token")

  for pattern in "${DENY_LIST[@]}"; do
    if is_prefix "$pattern" "$resolved"; then
      for allowed in "${ALLOW_LIST[@]}"; do
        is_prefix "$allowed" "$resolved" && continue 2 # continue on deny list
      done
      deny "tool call references a protected path: '$pattern'"
    fi

    if is_prefix "$resolved" "$pattern"; then
      deny "tool call references an ancestor of protected path: '$pattern'"
    fi
  done
done < <(grep -oE '/[^][:space:]"\;|&()<>,}]*' <<<"$normalized")
