# Code generated by AI (claude-sonnet-5)

from pathlib import Path
from typing import Any

def register(ctx: Any) -> None:
    skills_dir = Path(__file__).parent / "skills"
    for child in sorted(skills_dir.iterdir()):
        skill_md = child / "SKILL.md"
        if child.is_dir() and skill_md.exists():
            ctx.register_skill(child.name, skill_md)
