# Code generated by AI (claude-sonnet-5)

import json
import os
import subprocess

from pathlib import Path
from typing import Any

def _pre_llm_call(ctx: Any, **kwargs: Any) -> dict[str, str] | None:
    payload = json.dumps({"hook_event_name": "pre_llm_call", "cwd": os.getcwd()})
    try:
        result = subprocess.run(
            ["codebase-memory-mcp", "hook-augment", "--dialect", "hermes"],
            input=payload,
            check=False,
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        return None
    return {"context": result.stdout} if result.stdout else None

def register(ctx: Any) -> None:
    # `hook-augment --dialect hermes` only supports hook_event_name "pre_llm_call"
    ctx.register_hook("pre_llm_call", _pre_llm_call)

    skills_dir = Path(__file__).parent / "skills"
    for child in sorted(skills_dir.iterdir()):
        skill_md = child / "SKILL.md"
        if child.is_dir() and skill_md.exists():
            ctx.register_skill(child.name, skill_md)
