#!/usr/bin/env node
// Code generated by AI (Claude Sonnet 5)

'use strict'

const VALID_EVENTS = ['PreToolUse', 'PostToolUse', 'SessionStart', 'SubagentStart']
const message = 'Use context7-mcp skill for library docs. MCP unavailable? Fall back to the context7-cli skill.'

const main = () => {
    const eventName = process.argv[2] // comes from hooks calls

    if (!VALID_EVENTS.includes(eventName)) {
        process.stderr.write(`context7-hint: unknown hook event '${eventName}', expected one of ${VALID_EVENTS.join(', ')}`)
        process.exit(0)
    }

    switch (eventName) {
        // PreToolUse always ends with 'allow', this hook only serves as a reminder to agents (unknown keys are ignored, so one body covers them all).
        //
        // Runtime formats:
        //  - Claude Code, Codex: hookSpecificOutput wrapper (additionalContext honored)
        //  - Copilot: flat permissionDecision (no context field)
        //  - Cursor: flat permission (no context field)
        //  - Gemini: flat decision
        case 'PreToolUse':
            process.stdout.write(JSON.stringify({
                additionalContext: message,
                agent_message: message,
                context: message,
                decision: 'allow',
                message,
                permission: 'allow',
                permissionDecision: 'allow',
                hookSpecificOutput: {
                    hookEventName: eventName,
                    permissionDecision: 'allow',
                    additionalContext: message,
                },
            }))
            return
        // SessionStart, SubagentStart, PostToolUse inject context, no decision made.
        //
        // Runtime formats:
        //  - Claude Code, Codex, Devin: hookSpecificOutput wrapper
        //  - Copilot: flat top-level additionalContext
        //  - Cursor: flat snake_case additional_context (SessionStart only, SubagentStart has no context field on Cursor)
        case 'SessionStart':
        case 'SubagentStart':
        case 'PostToolUse':
            process.stdout.write(JSON.stringify({
                additionalContext: message,
                additional_context: message,
                context: message,
                hookSpecificOutput: {
                    hookEventName: eventName,
                    additionalContext: message,
                },
            }))
            return
    }
}

main()
