#!/usr/bin/env node
// Code generated by AI (claude-opus-5)

'use strict'

const { execFileSync } = require('node:child_process')
const fs = require('node:fs')

const message = 'Use codegraph-mcp skill for code discovery. MCP unavailable? Fall back to the codegraph-cli skill.'

const codegraph = (cwd, args) => {
    try {
        return execFileSync('codegraph', args, {
            cwd,
            encoding: 'utf8',
            timeout: 4000,
            stdio: ['ignore', 'pipe', 'ignore'],
        }).trim()
    } catch {
        return null
    }
}

const statusContext = (cwd, event) => {
    const stdout = codegraph(cwd, ['status', '-j'])
    const status = stdout ? JSON.parse(stdout) : null
    if (!status) {
        return null
    }

    if (!status.initialized) {
        const action = event === 'SubagentStart'
            ? 'ask parent agent to run `codegraph init --index`.'
            : 'run `codegraph init --index` to build one.'
        return `No codegraph index, ${action}. ${message}`
    }

    const pending = status.pendingChanges || {}
    const changed = (pending.added || 0) + (pending.modified || 0) + (pending.removed || 0)
    const stale = changed > 0 ? ` ${changed} file(s) changed, run 'codegraph sync'.` : ''
    return `codegraph indexed ${status.fileCount} files, ${status.nodeCount} symbols.${stale}. ${message}`
}

const main = (payload) => {
    const event = process.argv[2] // comes from hooks calls
    const cwd = typeof payload.cwd === 'string' ? payload.cwd : process.cwd()

    let context;
    switch (event) {
        // SessionStart, SubagentStart output format:
        //  - Claude Code, Codex, Devin: hookSpecificOutput wrapper
        //  - Copilot: flat top-level additionalContext
        //  - Cursor: flat snake_case additional_context (SessionStart only, SubagentStart has no context field on Cursor)
        //
        // Unknown keys are ignored by each agent, so one body covers them all.
        case 'SessionStart':
        case 'SubagentStart':
            context = statusContext(cwd, event)
            process.stdout.write(JSON.stringify({
                additionalContext: context,
                additional_context: context,
                context,
                hookSpecificOutput: {
                    hookEventName: event,
                    additionalContext: context,
                },
            }))
            break
        // PreToolUse output format:
        //  - Claude Code, Codex: hookSpecificOutput wrapper (additionalContext honored)
        //  - Copilot: flat permissionDecision (no context field)
        //  - Cursor: flat permission (no context field)
        //  - Gemini: flat decision
        //
        // Unknown keys are ignored by each agent, so one body covers them all.
        case 'PreToolUse':
            process.stdout.write(JSON.stringify({
                additionalContext: message,
                agent_message: message,
                context: message,
                decision: 'allow',
                message: message,
                permission: 'allow',
                permissionDecision: 'allow',
                hookSpecificOutput: {
                    hookEventName: event,
                    permissionDecision: 'allow',
                    additionalContext: message,
                },
            }))
            break
        // PostToolUse covers runtimes whose PreToolUse carries no context back to the agent (Copilot, Cursor)
        case 'PostToolUse':
            process.stdout.write(JSON.stringify({
                additionalContext: message,
                additional_context: message,
                context: message,
                hookSpecificOutput: {
                    hookEventName: event,
                    additionalContext: message,
                },
            }))
            break
    }
}

try {
    main(JSON.parse(fs.readFileSync(0, 'utf8')))
} catch {
    return
}
