# Code generated by AI (claude-sonnet-5)

from typing import Any

_MESSAGE = "Use context7-mcp skill for library docs. MCP unavailable? Fall back to the context7-cli skill."

def _pre_llm_call(ctx: Any, **kwargs: Any) -> dict[str, str]:
    return {"context": _MESSAGE}

def register(ctx: Any) -> None:
    ctx.register_hook("pre_llm_call", _pre_llm_call)
