# Code generated by AI (claude-sonnet-5)

from pathlib import Path
from typing import Any

_MESSAGE = "Use context7-mcp skill for library docs. MCP unavailable? Fall back to the context7-cli skill."

def _pre_llm_call(ctx: Any, **kwargs: Any) -> dict[str, str]:
    return {"context": _MESSAGE}

def register(ctx: Any) -> None:
    # pre_llm_call is the only Hermes hook that injects context
    ctx.register_hook("pre_llm_call", _pre_llm_call)

    skills_dir = Path(__file__).parent / "skills"
    for child in sorted(skills_dir.iterdir()):
        skill_md = child / "SKILL.md"
        if child.is_dir() and skill_md.exists():
            ctx.register_skill(child.name, skill_md)
