#!/usr/bin/env node
// Code generated by AI (claude-opus-5)

'use strict'

const VALID_EVENTS = ['PreToolUse', 'PostToolUse']
const message = 'Use codebase-memory skill for structural code discovery, prefixing its tools with `codebase-memory-mcp cli` when the MCP is unavailable.'

const main = () => {
    const eventName = process.argv[2] // comes from hooks calls

    if (!VALID_EVENTS.includes(eventName)) {
        process.stderr.write(`codebase-memory-hint: unknown hook event '${eventName}', expected one of ${VALID_EVENTS.join(', ')}`)
        process.exit(0)
    }

    // Two bodies (PreToolUse and PostToolUse), per each agent's own hooks docs.
    //
    // PreToolUse always ends with 'allow', this hook serves as a reminder to agents.
    //
    // PreToolUse output format:
    //  - Claude Code, Codex: hookSpecificOutput wrapper (additionalContext honored)
    //  - Copilot: flat permissionDecision (no context field)
    //  - Cursor: flat permission (no context field)
    //  - Gemini: flat decision
    //
    // PostToolUse output format:
    //  - Claude Code, Codex, Devin: hookSpecificOutput wrapper
    //  - Copilot: flat top-level additionalContext
    //  - Cursor: flat snake_case additional_context
    //
    // Unknown keys are ignored by each agent, so one body covers them all.
    const body = eventName === 'PreToolUse'
        ? {
            additionalContext: message,
            agent_message: message,
            context: message,
            decision: 'allow',
            message,
            permission: 'allow',
            permissionDecision: 'allow',
            hookSpecificOutput: {
                hookEventName: eventName,
                permissionDecision: 'allow',
                additionalContext: message,
            },
        }
        : {
            additionalContext: message,
            additional_context: message,
            context: message,
            hookSpecificOutput: {
                hookEventName: eventName,
                additionalContext: message,
            },
        }
    process.stdout.write(JSON.stringify(body))
}

main()
